### ISSUE TITLE
NoMemoryError during patch install

### ISSUE THREAD

**Issue by mrmarbury** [aririikonen/oracle#14]
Hi,

this is not so much an issue. I have this problem and wanted to ask, if you had the same problem and how did you fix it?

The VM I am using is a RHEL6 with 10GB ram and 8GB of swap space

During patchinstall with your cookbook, chef-client fills up the ram and then the swap and then the chef runs fails then with the following error

` Recipe: oracle::latest_dbpatch

           - execute service oracle stop

           - execute "bash"  "/tmp/chef-script20160219-4486-5l3lcx"

           - execute "bash"  "/tmp/chef-script20160219-4486-fhly0l"
         * execute[gen_response_file] action run

       ================================================================================
           Error executing action `run` on resource 'execute[gen_response_file]'
           ================================================================================

           RuntimeError
           ------------
           can't modify frozen NoMemoryError

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/oracle/recipes/latest_dbpatch.rb

            63:     execute 'gen_response_file' do
            64:       command "echo | ./OPatch/ocm/bin/emocmrsp -output ./ocm.rsp foo bar && chmod 0644 ./ocm.rsp"
            65:       user "oracle"
            66:       group 'oinstall'
            67:       cwd node[:oracle][:rdbms][:ora_home]
            68:     end
            69:   end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/oracle/recipes/latest_dbpatch.rb:63:in `from_file'

           execute("gen_response_file") do
             action [:run]
             retries 0
             retry_delay 2
             default_guard_interpreter :execute
             command "echo | ./OPatch/ocm/bin/emocmrsp -output ./ocm.rsp foo bar && chmod 0644 ./ocm.rsp"
             backup 5
             cwd "/opt/oracle/11R23"
             group "oinstall"
             returns 0
             user "oracle"
             declared_type :execute
             cookbook_name "oracle"
             recipe_name "latest_dbpatch"
           end

       Running handlers:
       [2016-02-19T14:47:44+01:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-02-19T14:47:44+01:00] ERROR: Exception handlers complete
       Chef Client failed. 3 resources updated in 01 hours 15 minutes 23 seconds
       [2016-02-19T14:47:44+01:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-02-19T14:47:44+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-02-19T14:47:44+01:00] ERROR: execute[gen_response_file] (oracle::latest_dbpatch line 63) had an error: RuntimeError: can't modify frozen NoMemoryError
       [2016-02-19T14:47:50+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
`

Here is the output from top, shortly before the crash. RAM is full and SWAP fills as well. 

`top - 17:15:06 up 45 min,  2 users,  load average: 1.38, 1.44, 1.32
Tasks: 108 total,   3 running, 105 sleeping,   0 stopped,   0 zombie
Cpu(s): 68.5%us, 14.0%sy,  0.0%ni, 13.0%id,  4.3%wa,  0.0%hi,  0.2%si,  0.0%st
Mem:  10122208k total,  9961848k used,   160360k free,      120k buffers
Swap:  8392672k total,   537004k used,  7855668k free,    12620k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 3787 root      20   0 15.0g 9.2g 1624 R 95.9 95.1  39:16.67 chef-client
 4782 oracle    20   0 1966m  89m 8396 R 63.1  0.9  26:18.88 java
`

Did you encounter the same error? What did you do to fix this? 

Thx for your support,
Stefan

**Comment by aririikonen** [comment]
I believe this is related to the way ocm.rsp file is generated. In the cookbook, it follows the Oracle documentation instructions, but I've found out that this requires internet access (proxy access). What I've done at our work, where we have the same issue, is that I've replaced this resource with a pre made ocm.rsp file and I'm just placing it to the same location with `'cookbook_file'` resource. Obvioulsy you need to create the ocm.rsp file first and place it under `coobooks/oracle/files/default` first.

```
  # Making sure ocm.rsp response file is present.
  cookbook_file "#{node[:oracle][:rdbms][:ora_home]}/ocm.rsp" do
    source 'ocm.rsp'
    owner 'oracle'
    group 'oinstall'
    mode '0644'
  end
```

**Comment by mrmarbury** [comment]
... oracle ... always fun (not). Thank you :) I will try this on monday. Have a nice weekend.

**Comment by aririikonen** [comment]
Oracle is like grass, it keeps on growing unless you cut it with scissors...

**Comment by mrmarbury** [comment]
well creating the file myself works. It's pretty rediculous though when you think about what this file really contains in the end ^^ 

Thx :)
